# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.




development:
  pubnub_subscribe_key: sub-c-fad25034-2fff-11e6-a01f-0619f8945a4f
  pubnub_publish_key: pub-c-f2e03eea-5e49-4b5f-ad47-96cb857821d8
  pubnub_secret_key: sec-c-OWJiMjg0MjktZWI2MS00MWVjLWE0MGQtYzFiN2MwYWVmNDY4
  pubnub_auth_key: cachirula
  secret_key_base: 52f0094733b0ed1dc0d98a7c7742597c104493d58ed0b2df2861396b415f8c40c9f71f89b4ea6972af7dde2dd49f2aba45dcf531591f627328f72b48b94b92c3


test:

  secret_key_base: 20f493e0cd244aad74c57474e3d4b751263de79d1bd0297cd899905d6e079c66079556b0433682f8276d7a1f42428c797b1c41f8a368c52350e02ceb78463169

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  pubnub_subscribe_key: sub-c-fad25034-2fff-11e6-a01f-0619f8945a4f
  pubnub_publish_key: pub-c-f2e03eea-5e49-4b5f-ad47-96cb857821d8
  pubnub_secret_key: sec-c-OWJiMjg0MjktZWI2MS00MWVjLWE0MGQtYzFiN2MwYWVmNDY4
  pubnub_auth_key: cachirula
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

